# Generated by Django 4.2.6 on 2023-10-09 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentsGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="school.group"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="school.student"
                    ),
                ),
            ],
        ),
    ]
