# Generated by Django 4.2.6 on 2023-10-09 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0003_studentsgroup"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentsgroup",
            old_name="group_id",
            new_name="group",
        ),
        migrations.RenameField(
            model_name="studentsgroup",
            old_name="student_id",
            new_name="student",
        ),
    ]
