# Generated by Django 4.2.6 on 2023-10-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0004_rename_group_id_studentsgroup_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
